[tool.black]
line-length = 88
target-version = ["py310"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["src", "entities", "reposiotries", "tests", "infrastructure"]
known_third_party = ["fastapi", "pydantic"]
combine_as_imports = true
